[package]
name = "gnomePods"
version = "0.1.5"
edition = "2024"

authors = ["Can Boluk <me@can.ac>", "Amilie <amilie@amilie.gay>"]
description = "D-Bus service for AirPods management in GNOME"
license = "GPL-3.0-or-later"

homepage = "https://github.com/AmilieCoding/gnomePods"
repository = "https://github.com/AmilieCoding/gnomePods"
documentation = "https://github.com/AmilieCoding/gnomePods"
readme = "../README.md"

keywords = ["gnome", "airpods", "bluetooth", "dbus"]
categories = ["hardware-support", "desktop", "os::linux-apis"]

[dependencies]
tokio = { version = "1.47", features = ["full"] }
zbus = { version = "5.9", features = ["tokio"] }
bluer = { version = "0.17", features = ["l2cap", "bluetoothd"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2"
log = "0.4"
env_logger = "0.11"
hex = "0.4"
futures = "0.3"
toml = "0.9"
crossbeam = { version = "0.8", features = ["std"] }
parking_lot = "0.12"
heapless = "0.8"
smallvec = "1.10"
smol_str = { version = "0.3", features = ["serde"] }
rand = "0.8"
strum = { version = "0.27", features = ["derive"] }
heed = { version = "0.22", features = ["serde-bincode"] }
dirs = "6.0"
gtk = { version = "0.10.0", package = "gtk4", features = ["v4_12"] }
glib = "0.21.0"

[dev-dependencies]
tempfile = "3.14"

[[bin]]
name = "gnomePods"
path = "src/main.rs"
